<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_lEjEoAcUEey8o8GE9SBwWw" name="MyDiagram" author="adrien" bonitaVersion="7.13.0" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_lEjEoQcUEey8o8GE9SBwWw" name="FirstProcess">
      <elements xmi:type="process:Lane" xmi:id="_lEjEogcUEey8o8GE9SBwWw" name="Employee lane" actor="_lEjrwwcUEey8o8GE9SBwWw">
        <elements xmi:type="process:StartEvent" xmi:id="_lEjEowcUEey8o8GE9SBwWw" name="Start1" outgoing="_lEjrwAcUEey8o8GE9SBwWw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_lEjEpAcUEey8o8GE9SBwWw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_lEjEpQcUEey8o8GE9SBwWw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_lEjEpgcUEey8o8GE9SBwWw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_lEjEpwcUEey8o8GE9SBwWw" name="Step1" outgoing="_EINOUAczEeygtq0Q5KasDA" incoming="_lEjrwAcUEey8o8GE9SBwWw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_lEjrsAcUEey8o8GE9SBwWw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_lEjrsQcUEey8o8GE9SBwWw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_lEjrsgcUEey8o8GE9SBwWw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_lEjrswcUEey8o8GE9SBwWw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_lEjrtAcUEey8o8GE9SBwWw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_lEjrtQcUEey8o8GE9SBwWw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_lEjrtgcUEey8o8GE9SBwWw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_lEjrtwcUEey8o8GE9SBwWw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_lEjruAcUEey8o8GE9SBwWw">
            <targetForm xmi:type="expression:Expression" xmi:id="_lEjruQcUEey8o8GE9SBwWw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_lEjrugcUEey8o8GE9SBwWw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_lEjruwcUEey8o8GE9SBwWw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_EGnS4AczEeygtq0Q5KasDA" name="End1" incoming="_EINOUAczEeygtq0Q5KasDA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_EG0uQQczEeygtq0Q5KasDA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_EG0uQAczEeygtq0Q5KasDA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_EG0uQgczEeygtq0Q5KasDA" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_lEjrvAcUEey8o8GE9SBwWw">
        <targetForm xmi:type="expression:Expression" xmi:id="_lEjrvQcUEey8o8GE9SBwWw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_lEjrvgcUEey8o8GE9SBwWw">
        <targetForm xmi:type="expression:Expression" xmi:id="_lEjrvwcUEey8o8GE9SBwWw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_lEjrwAcUEey8o8GE9SBwWw" target="_lEjEpwcUEey8o8GE9SBwWw" source="_lEjEowcUEey8o8GE9SBwWw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_lEjrwQcUEey8o8GE9SBwWw"/>
        <condition xmi:type="expression:Expression" xmi:id="_lEjrwgcUEey8o8GE9SBwWw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_EINOUAczEeygtq0Q5KasDA" target="_EGnS4AczEeygtq0Q5KasDA" source="_lEjEpwcUEey8o8GE9SBwWw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_EIN1YAczEeygtq0Q5KasDA"/>
        <condition xmi:type="expression:Expression" xmi:id="_EIN1YQczEeygtq0Q5KasDA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_lEjrwwcUEey8o8GE9SBwWw" documentation="This is an example of actor that is mapped to any ACME users" name="Employee actor" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_lEjrxAcUEey8o8GE9SBwWw"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_lEjrxQcUEey8o8GE9SBwWw">
        <name xmi:type="expression:Expression" xmi:id="_lEjrxgcUEey8o8GE9SBwWw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_lEjrxwcUEey8o8GE9SBwWw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_lEjryAcUEey8o8GE9SBwWw">
        <name xmi:type="expression:Expression" xmi:id="_lEjryQcUEey8o8GE9SBwWw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_lEjrygcUEey8o8GE9SBwWw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_lEjrywcUEey8o8GE9SBwWw">
        <name xmi:type="expression:Expression" xmi:id="_lEjrzAcUEey8o8GE9SBwWw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_lEjrzQcUEey8o8GE9SBwWw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_lEjrzgcUEey8o8GE9SBwWw">
        <name xmi:type="expression:Expression" xmi:id="_lEjrzwcUEey8o8GE9SBwWw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_lEjr0AcUEey8o8GE9SBwWw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_lEjr0QcUEey8o8GE9SBwWw">
        <name xmi:type="expression:Expression" xmi:id="_lEjr0gcUEey8o8GE9SBwWw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_lEjr0wcUEey8o8GE9SBwWw" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_sAzzsAc2EeyXds4CwRbf5A" name="SecondProcess">
      <elements xmi:type="process:Lane" xmi:id="_sZ-hoAc2EeyXds4CwRbf5A" name="Lane1">
        <elements xmi:type="process:StartEvent" xmi:id="_sqMu8Ac2EeyXds4CwRbf5A" name="Start2" outgoing="_s3ouAAc2EeyXds4CwRbf5A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_sqNWAQc2EeyXds4CwRbf5A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_sqNWAAc2EeyXds4CwRbf5A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_sqNWAgc2EeyXds4CwRbf5A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_s3XBMAc2EeyXds4CwRbf5A" name="Step2" outgoing="_tCesEAc2EeyXds4CwRbf5A" incoming="_s3ouAAc2EeyXds4CwRbf5A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_s3XBMgc2EeyXds4CwRbf5A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_s3XBMQc2EeyXds4CwRbf5A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_s3XBMwc2EeyXds4CwRbf5A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_s3XBNAc2EeyXds4CwRbf5A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_s3XBNQc2EeyXds4CwRbf5A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_s3XBNgc2EeyXds4CwRbf5A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_s3XBOAc2EeyXds4CwRbf5A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_s3XBNwc2EeyXds4CwRbf5A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_tCaaoAc2EeyXds4CwRbf5A" name="Step3" outgoing="_tMT9gAc2EeyXds4CwRbf5A" incoming="_tCesEAc2EeyXds4CwRbf5A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_tCaaogc2EeyXds4CwRbf5A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_tCaaoQc2EeyXds4CwRbf5A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_tCaaowc2EeyXds4CwRbf5A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_tCaapAc2EeyXds4CwRbf5A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_tCaapQc2EeyXds4CwRbf5A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_tCaapgc2EeyXds4CwRbf5A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_tCaaqAc2EeyXds4CwRbf5A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_tCaapwc2EeyXds4CwRbf5A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_tMNP0Ac2EeyXds4CwRbf5A" name="Step4" outgoing="_tX47YAc2EeyXds4CwRbf5A" incoming="_tMT9gAc2EeyXds4CwRbf5A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_tMNP0gc2EeyXds4CwRbf5A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_tMNP0Qc2EeyXds4CwRbf5A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_tMNP0wc2EeyXds4CwRbf5A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_tMNP1Ac2EeyXds4CwRbf5A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_tMNP1Qc2EeyXds4CwRbf5A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_tMNP1gc2EeyXds4CwRbf5A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_tMNP2Ac2EeyXds4CwRbf5A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_tMNP1wc2EeyXds4CwRbf5A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_tXw_kAc2EeyXds4CwRbf5A" name="Step5" outgoing="_tvgKIAc2EeyXds4CwRbf5A" incoming="_tX47YAc2EeyXds4CwRbf5A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_tXw_kgc2EeyXds4CwRbf5A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_tXw_kQc2EeyXds4CwRbf5A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_tXw_kwc2EeyXds4CwRbf5A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_tXw_lAc2EeyXds4CwRbf5A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_tXw_lQc2EeyXds4CwRbf5A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_tXw_lgc2EeyXds4CwRbf5A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_tXw_mAc2EeyXds4CwRbf5A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_tXw_lwc2EeyXds4CwRbf5A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_tvaqkAc2EeyXds4CwRbf5A" name="End2" incoming="_tvgKIAc2EeyXds4CwRbf5A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_tvbRoQc2EeyXds4CwRbf5A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_tvbRoAc2EeyXds4CwRbf5A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_tvbRogc2EeyXds4CwRbf5A" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_sEc9ngc2EeyXds4CwRbf5A">
        <targetForm xmi:type="expression:Expression" xmi:id="_sEc9nwc2EeyXds4CwRbf5A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_sEc9oAc2EeyXds4CwRbf5A">
        <targetForm xmi:type="expression:Expression" xmi:id="_sEc9oQc2EeyXds4CwRbf5A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_s3ouAAc2EeyXds4CwRbf5A" target="_s3XBMAc2EeyXds4CwRbf5A" source="_sqMu8Ac2EeyXds4CwRbf5A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_s3ouAQc2EeyXds4CwRbf5A"/>
        <condition xmi:type="expression:Expression" xmi:id="_s3ouAgc2EeyXds4CwRbf5A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_tCesEAc2EeyXds4CwRbf5A" target="_tCaaoAc2EeyXds4CwRbf5A" source="_s3XBMAc2EeyXds4CwRbf5A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_tCesEQc2EeyXds4CwRbf5A"/>
        <condition xmi:type="expression:Expression" xmi:id="_tCesEgc2EeyXds4CwRbf5A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_tMT9gAc2EeyXds4CwRbf5A" target="_tMNP0Ac2EeyXds4CwRbf5A" source="_tCaaoAc2EeyXds4CwRbf5A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_tMVLoAc2EeyXds4CwRbf5A"/>
        <condition xmi:type="expression:Expression" xmi:id="_tMVLoQc2EeyXds4CwRbf5A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_tX47YAc2EeyXds4CwRbf5A" target="_tXw_kAc2EeyXds4CwRbf5A" source="_tMNP0Ac2EeyXds4CwRbf5A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_tX5icAc2EeyXds4CwRbf5A"/>
        <condition xmi:type="expression:Expression" xmi:id="_tX5icQc2EeyXds4CwRbf5A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_tvgKIAc2EeyXds4CwRbf5A" target="_tvaqkAc2EeyXds4CwRbf5A" source="_tXw_kAc2EeyXds4CwRbf5A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_tvgKIQc2EeyXds4CwRbf5A"/>
        <condition xmi:type="expression:Expression" xmi:id="_tvgKIgc2EeyXds4CwRbf5A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <contract xmi:type="process:Contract" xmi:id="_sEc9ogc2EeyXds4CwRbf5A"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_sEcWgAc2EeyXds4CwRbf5A">
        <name xmi:type="expression:Expression" xmi:id="_sEc9kAc2EeyXds4CwRbf5A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_sEc9kQc2EeyXds4CwRbf5A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_sEc9kgc2EeyXds4CwRbf5A">
        <name xmi:type="expression:Expression" xmi:id="_sEc9kwc2EeyXds4CwRbf5A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_sEc9lAc2EeyXds4CwRbf5A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_sEc9lQc2EeyXds4CwRbf5A">
        <name xmi:type="expression:Expression" xmi:id="_sEc9lgc2EeyXds4CwRbf5A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_sEc9lwc2EeyXds4CwRbf5A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_sEc9mAc2EeyXds4CwRbf5A">
        <name xmi:type="expression:Expression" xmi:id="_sEc9mQc2EeyXds4CwRbf5A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_sEc9mgc2EeyXds4CwRbf5A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_sEc9mwc2EeyXds4CwRbf5A">
        <name xmi:type="expression:Expression" xmi:id="_sEc9nAc2EeyXds4CwRbf5A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_sEc9nQc2EeyXds4CwRbf5A" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_lEjr1AcUEey8o8GE9SBwWw" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_lEjr1QcUEey8o8GE9SBwWw" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_lEjr1gcUEey8o8GE9SBwWw" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_lEjr1wcUEey8o8GE9SBwWw" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_lEjr2AcUEey8o8GE9SBwWw" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_lEjr2QcUEey8o8GE9SBwWw" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_lEjr2gcUEey8o8GE9SBwWw" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_lEjr2wcUEey8o8GE9SBwWw" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_lEjr3AcUEey8o8GE9SBwWw" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_lEjr3QcUEey8o8GE9SBwWw" type="Process" element="_lEjEoAcUEey8o8GE9SBwWw" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_lEjr3gcUEey8o8GE9SBwWw" type="2007" element="_lEjEoQcUEey8o8GE9SBwWw">
      <children xmi:type="notation:DecorationNode" xmi:id="_lEjr3wcUEey8o8GE9SBwWw" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_lEjr4AcUEey8o8GE9SBwWw" type="7001">
        <children xmi:type="notation:Node" xmi:id="_lEjr4QcUEey8o8GE9SBwWw" type="3007" element="_lEjEogcUEey8o8GE9SBwWw">
          <children xmi:type="notation:DecorationNode" xmi:id="_lEjr4gcUEey8o8GE9SBwWw" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_lEjr4wcUEey8o8GE9SBwWw" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_lEjr5AcUEey8o8GE9SBwWw" type="3005" element="_lEjEpwcUEey8o8GE9SBwWw" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_lEjr5QcUEey8o8GE9SBwWw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_lEjr5gcUEey8o8GE9SBwWw" x="160" y="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_lEjr5wcUEey8o8GE9SBwWw" type="3002" element="_lEjEowcUEey8o8GE9SBwWw" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_lEjr6AcUEey8o8GE9SBwWw" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_lEjr6QcUEey8o8GE9SBwWw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_lEjr6gcUEey8o8GE9SBwWw" x="60" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_EH33IAczEeygtq0Q5KasDA" type="3062" element="_EGnS4AczEeygtq0Q5KasDA" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_EH4eMAczEeygtq0Q5KasDA" type="5090">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_EH4eMQczEeygtq0Q5KasDA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_EH33IQczEeygtq0Q5KasDA" x="353" y="73"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_lEjr6wcUEey8o8GE9SBwWw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_lEjr7AcUEey8o8GE9SBwWw" fontName=".AppleSystemUIFont"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_lEjr7QcUEey8o8GE9SBwWw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_lEjr7gcUEey8o8GE9SBwWw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_lEjr7wcUEey8o8GE9SBwWw"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_lEjr8AcUEey8o8GE9SBwWw"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_lEjr8QcUEey8o8GE9SBwWw" fontName=".AppleSystemUIFont"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_lEjr8gcUEey8o8GE9SBwWw"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_lEjr8wcUEey8o8GE9SBwWw"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_lEjr9AcUEey8o8GE9SBwWw" width="1320" height="250"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_sErnEAc2EeyXds4CwRbf5A" type="2007" element="_sAzzsAc2EeyXds4CwRbf5A">
      <children xmi:type="notation:DecorationNode" xmi:id="_sEsOIwc2EeyXds4CwRbf5A" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_sEsOJAc2EeyXds4CwRbf5A" type="7001">
        <children xmi:type="notation:Node" xmi:id="_sZ_IsAc2EeyXds4CwRbf5A" type="3007" element="_sZ-hoAc2EeyXds4CwRbf5A">
          <children xmi:type="notation:DecorationNode" xmi:id="_sZ_vwAc2EeyXds4CwRbf5A" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_sZ_vwQc2EeyXds4CwRbf5A" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_sqN9EAc2EeyXds4CwRbf5A" type="3002" element="_sqMu8Ac2EeyXds4CwRbf5A" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_sqOkIAc2EeyXds4CwRbf5A" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_sqOkIQc2EeyXds4CwRbf5A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_sqN9EQc2EeyXds4CwRbf5A" x="114" y="109"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_s3YPUAc2EeyXds4CwRbf5A" type="3027" element="_s3XBMAc2EeyXds4CwRbf5A" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_s3YPUgc2EeyXds4CwRbf5A" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_s3YPUQc2EeyXds4CwRbf5A" x="224" y="69"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_tCbBsAc2EeyXds4CwRbf5A" type="3027" element="_tCaaoAc2EeyXds4CwRbf5A" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_tCbowAc2EeyXds4CwRbf5A" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_tCbBsQc2EeyXds4CwRbf5A" x="429" y="57"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_tMOd8Ac2EeyXds4CwRbf5A" type="3027" element="_tMNP0Ac2EeyXds4CwRbf5A" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_tMOd8gc2EeyXds4CwRbf5A" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_tMOd8Qc2EeyXds4CwRbf5A" x="644" y="54"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_tXyNsAc2EeyXds4CwRbf5A" type="3027" element="_tXw_kAc2EeyXds4CwRbf5A" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_tXy0wAc2EeyXds4CwRbf5A" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_tXyNsQc2EeyXds4CwRbf5A" x="829" y="62"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_tvb4sAc2EeyXds4CwRbf5A" type="3062" element="_tvaqkAc2EeyXds4CwRbf5A" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_tvb4sgc2EeyXds4CwRbf5A" type="5090">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_tvcfwAc2EeyXds4CwRbf5A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_tvb4sQc2EeyXds4CwRbf5A" x="1016" y="133"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_sZ_IsQc2EeyXds4CwRbf5A"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_sZ_Isgc2EeyXds4CwRbf5A" fontName=".AppleSystemUIFont"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_sZ_Iswc2EeyXds4CwRbf5A"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_sZ_vwgc2EeyXds4CwRbf5A"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_sZ_ItAc2EeyXds4CwRbf5A" x="194" y="99"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_sErnEQc2EeyXds4CwRbf5A"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_sEsOIAc2EeyXds4CwRbf5A" fontName=".AppleSystemUIFont"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_sEsOIQc2EeyXds4CwRbf5A"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_sEs1MAc2EeyXds4CwRbf5A"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_sEsOIgc2EeyXds4CwRbf5A" width="1320" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_lEjr9QcUEey8o8GE9SBwWw"/>
    <edges xmi:type="notation:Connector" xmi:id="_lEjr9gcUEey8o8GE9SBwWw" type="4001" element="_lEjrwAcUEey8o8GE9SBwWw" source="_lEjr5wcUEey8o8GE9SBwWw" target="_lEjr5AcUEey8o8GE9SBwWw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_lEjr9wcUEey8o8GE9SBwWw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_lEjr-AcUEey8o8GE9SBwWw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_lEjr-QcUEey8o8GE9SBwWw" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_lEjr-gcUEey8o8GE9SBwWw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_EIPDgAczEeygtq0Q5KasDA" type="4001" element="_EINOUAczEeygtq0Q5KasDA" source="_lEjr5AcUEey8o8GE9SBwWw" target="_EH33IAczEeygtq0Q5KasDA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_EIPqkAczEeygtq0Q5KasDA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_EIPqkQczEeygtq0Q5KasDA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_EIPDgQczEeygtq0Q5KasDA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_EIPDggczEeygtq0Q5KasDA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_s3p8IAc2EeyXds4CwRbf5A" type="4001" element="_s3ouAAc2EeyXds4CwRbf5A" source="_sqN9EAc2EeyXds4CwRbf5A" target="_s3YPUAc2EeyXds4CwRbf5A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_s3qjMAc2EeyXds4CwRbf5A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_s3qjMQc2EeyXds4CwRbf5A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_s3p8IQc2EeyXds4CwRbf5A" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_s3p8Igc2EeyXds4CwRbf5A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_tCfTIAc2EeyXds4CwRbf5A" type="4001" element="_tCesEAc2EeyXds4CwRbf5A" source="_s3YPUAc2EeyXds4CwRbf5A" target="_tCbBsAc2EeyXds4CwRbf5A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_tCfTIwc2EeyXds4CwRbf5A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_tCfTJAc2EeyXds4CwRbf5A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_tCfTIQc2EeyXds4CwRbf5A" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_tCfTIgc2EeyXds4CwRbf5A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_tMVysAc2EeyXds4CwRbf5A" type="4001" element="_tMT9gAc2EeyXds4CwRbf5A" source="_tCbBsAc2EeyXds4CwRbf5A" target="_tMOd8Ac2EeyXds4CwRbf5A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_tMWZwAc2EeyXds4CwRbf5A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_tMWZwQc2EeyXds4CwRbf5A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_tMVysQc2EeyXds4CwRbf5A" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_tMVysgc2EeyXds4CwRbf5A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_tX6JgAc2EeyXds4CwRbf5A" type="4001" element="_tX47YAc2EeyXds4CwRbf5A" source="_tMOd8Ac2EeyXds4CwRbf5A" target="_tXyNsAc2EeyXds4CwRbf5A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_tX6Jgwc2EeyXds4CwRbf5A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_tX6JhAc2EeyXds4CwRbf5A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_tX6JgQc2EeyXds4CwRbf5A" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_tX6Jggc2EeyXds4CwRbf5A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_tvgxMAc2EeyXds4CwRbf5A" type="4001" element="_tvgKIAc2EeyXds4CwRbf5A" source="_tXyNsAc2EeyXds4CwRbf5A" target="_tvb4sAc2EeyXds4CwRbf5A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_tvgxMwc2EeyXds4CwRbf5A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_tvgxNAc2EeyXds4CwRbf5A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_tvgxMQc2EeyXds4CwRbf5A" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_tvgxMgc2EeyXds4CwRbf5A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
